feat!: package rename in npm
googleapis/nodejs-resource pull request #370
Opened 2021-05-04 20:59 UTC by sofisl

Addresses #364

2021-05-04 22:42 UTC, bcoe requested changes

2021-05-04 22:42 UTC, bcoe commented on README.md
> +**Version 3.0.0 renames `@google-cloud/resource` to `@google-cloud/resource-manager` on npm.**
Based on discussion that we'll not bump the major twice:

```suggestion
**Version 2.0.0 renames `@google-cloud/resource` to `@google-cloud/resource-manager` on npm.**
```

2021-05-05 17:46 UTC, bcoe approved these changes

2021-05-21 23:04 UTC, sofisl commented
@bcoe, would you mind confirming these changes one more time? I had to make all the changes to the repo's names at once, since they changed in google3.

2021-05-22 02:33 UTC, merged